# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
default_language_version:
  python: python3
minimum_pre_commit_version: "2.10.1"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
        types: [text]
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
      - id: vulture

  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        args: ["--profile", "black", "-l", "99"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "99"]
        additional_dependencies:
          - flake8-logging-format
          - flake8-print

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.12.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: local
    hooks:
      - id: shellcheck
        name: Check Shell scripts syntax correctness
        language: docker_image
        entry: koalaman/shellcheck:stable -x -a
        files: \.sh$|\.bash$
