[build-system]
requires = [
    "setuptools>=58",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.vulture]
exclude = ["ENV/", "tests/"]
min_confidence = 70
paths = ["."]

[tool.black]
line-length=99

[tool.isort]
profile = "black"

[tool.pylint.format]
extend-ignore = "E203"
